name: settings_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ^3.38.0

dependencies:
  appwrite: ^20.0.0
  appwrite_repository:
    path: ../appwrite_repository
  file_picker: ^10.3.2
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  log_repository:
    path: ../log_repository

dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  json_serializable: ^6.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

